training:
  model_save_path: "./trained_models/keras_test_unet"
  sample_label_path: "./data/sample_data/labels"
  sample_image_path: "./data/sample_data/images"
  model:
    compile_params:
      optimizer: "rmsprop" # https://www.tensorflow.org/api_docs/python/tf/keras/optimizers
      loss: "categorical_crossentropy" # https://www.tensorflow.org/api_docs/python/tf/keras/losses
      metrics:
        - "accuracy"
        - "Precision"
        - "Recall"
#        - "mse"
#        - "FalsePositives"
#        - "FalseNegatives"
    fit_params:
      epochs: 500
      steps_per_epoch: 1
      verbose: 2
#      loss_weights: None
#      weighted_metrics: ...
#      run_eagerly: ...
#      steps_per_execution: ...
#      jit_compile: ...
